name: champagnejulep
description: descriptions
publish_to: 'none'
version: 0.1.1+1
environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  # Basic
  cupertino_icons: ^1.0.2
  collection: ^1.17.0
  intl: ^0.18.1
  path_provider: ^2.0.15
  share_plus: ^7.0.2
  json_annotation: ^4.8.0
  uuid: ^3.0.7
  freezed_annotation: ^2.2.0
  # Firebase
  firebase_core: ^2.10.0
  # Ads
  # Database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  # Dependency Injection
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  # Others
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # Testing
  # Building
  build_runner: ^2.3.3
  riverpod_generator: ^2.2.3
  isar_generator: ^3.1.0+1
  # Meta
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.19
  # Others
  freezed: ^2.3.2
  json_serializable: ^6.6.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/ic_launcher.png"
flutter_native_splash:
  color: "#FEF8EE"
  image: "assets/images/ic_launcher.png"