name: champagnejurep
description: descriptions
publish_to: 'none'
version: 0.0.1+1
environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
  cupertino_icons: ^1.0.2
  # Firebase
  # Ads
  # Database

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # Testing
  # Building
  # Meta
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/