name: Chore

on:
  push:
    branches-ignore:
      - 'main'

env:
  FLUTTER_VERSION: '3.7.12'
  WORKING_FLUTTER_DIRECTORY: 'flutter'

jobs:
  flutter_formatter:
    name: Flutter formatter
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
      - working-directory: ${{ env.WORKING_FLUTTER_DIRECTORY }}
        run: flutter pub get
      - working-directory: ${{ env.WORKING_FLUTTER_DIRECTORY }}
        run: flutter format --line-length=120 ./lib/ ./test/
  flutter_build_runner:
    name: Flutter build runner
    needs: [flutter_formatter]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
      - working-directory: ${{ env.WORKING_FLUTTER_DIRECTORY }}
        run: flutter pub get
      - working-directory: ${{ env.WORKING_FLUTTER_DIRECTORY }}
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[chore] Flutter Auto Format, Build Runner'
